# Generated by Django 5.2.4 on 2026-05-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها '},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='tag',
            new_name='tags',
        ),
    ]
