# Generated by Django 5.2.4 on 2026-05-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_tags_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
