# Generated by Django 5.2.4 on 2026-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_deleted_at_note_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آرشیو'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='آرشیوشده'),
        ),
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف '),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
