# Generated by Django 5.2.4 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_noteshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshare',
            name='moved_to_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
