# Generated by Django 5.2.4 on 2026-06-01 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_noteshare_moved_to_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshare',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_received_in_dashboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
