# Generated by Django 5.2.4 on 2026-06-01 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_noteshare_received_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteshare',
            name='received_from',
        ),
        migrations.AddField(
            model_name='note',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notes', to=settings.AUTH_USER_MODEL, verbose_name='دریافت شده از'),
        ),
    ]
