# Generated by Django 5.2.4 on 2026-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_remove_noteshare_received_from_note_received_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notes/attachments/', verbose_name='فایل ضمیمه'),
        ),
    ]
