# Generated by Django 5.2.4 on 2026-06-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_noteattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteShare',
        ),
    ]
