# Generated by Django 5.2.4 on 2026-06-08 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_delete_noteshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteattachment',
            options={'verbose_name': 'فایل ضمیمه', 'verbose_name_plural': 'فایل\u200cهای ضمیمه'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب\u200cها'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='آرشیو شده'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='notes_note_user_id_65a850_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_deleted'], name='notes_note_user_id_727199_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived'], name='notes_note_user_id_d0efd6_idx'),
        ),
        migrations.AddIndex(
            model_name='noteattachment',
            index=models.Index(fields=['note', '-created_at'], name='notes_notea_note_id_1fb8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='notes_tag_user_id_86aeef_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_tag'),
        ),
    ]
