# Generated by Django 5.2.4 on 2026-06-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_noteattachment_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='received_from',
        ),
    ]
