# Generated by Django 5.2.15 on 2026-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_user_role_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', help_text="Designates the user's role in the system.", max_length=20, verbose_name='role'),
        ),
    ]
