"""
Django settings for noteapp2 project.
<<<<<<< HEAD

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
=======
"""

from pathlib import Path
from datetime import timedelta
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

=======
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o0ylqomj8pla81)tkwdg%*$_0r^0iw$q-5594okg+j0f(&irnu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    "rest_framework_simplejwt",
=======
# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# یا برای محدود کردن فقط به فرانت لوکال:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_select2',
    'apps.notes',
    'apps.accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
<<<<<<< HEAD
    


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
=======

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # بالای همه
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF می‌تواند باقی بماند، JWT نیازی به CSRF ندارد
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noteapp2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [
            
                BASE_DIR / "templates"
            
        ],
=======
        'DIRS': [BASE_DIR / "templates"],
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noteapp2.wsgi.application'

<<<<<<< HEAD

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

=======
# Database
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / "static"
]


AUTH_USER_MODEL = "accounts.User"



LOGOUT_REDIRECT_URL = "login"
LOGIN_URL = "login"

MEDIA_ROOT = BASE_DIR / "uploads"
MEDIA_URL = "/files/"



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework.authentication.SessionAuthentication',
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
=======
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
MEDIA_ROOT = BASE_DIR / "uploads"
MEDIA_URL = "/files/"

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Login/Logout redirects
LOGOUT_REDIRECT_URL = "login"
LOGIN_URL = "login"

# ------------------------------
# REST Framework configuration
# ------------------------------
REST_FRAMEWORK = {
    # فقط JWT authentication برای API ها
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # پیش‌فرض همه API ها نیاز به auth دارند مگر AllowAny مشخص شود
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

<<<<<<< HEAD

=======
# Swagger / DRF spectacular
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
SPECTACULAR_SETTINGS = {
    'TITLE': 'NoteApp2 API Documentation',
    'DESCRIPTION': 'مدیریت نوت‌ها، تگ‌ها و ضمائم پروژه NoteApp2',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
<<<<<<< HEAD
    # این گزینه باعث می‌شود داکیومنت مرتب‌تر باشد
=======
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}

<<<<<<< HEAD

from datetime import timedelta

=======
# JWT settings
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
<<<<<<< HEAD
}
=======
}
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
>>>>>>> 9189de6f6e0efed64d09b8bbd24ee2ef0702541e
